from setuptools import setup, find_packages

setup(
    name="interpret-clone",
    version="0.1.0",
    description="Un clon modificado de interpretml",
    author="Javier Pérez Vargas",
    author_email="javipv2003pv@gmail.com",
    url="https://github.com/bmihaljevic/tfg-interpretml",
    packages=find_packages(include=["interpret", "interpret.*"]),
    install_requires=[
        "aplr==10.8.0",
        "azure_storage==0.37.0",
        "catboost==1.2.7",
        "cryptography==44.0.2",
        "dash==2.18.2",
        "dash_cytoscape==1.0.2",
        "Flask==2.2.2",
        "gevent==24.11.1",
        "ipykernel==6.29.5",
        "ipython==8.18.1",
        "ipywidgets==8.1.5",
        "joblib==1.4.2",
        "jupyter_packaging==0.12.3",
        "lime==0.2.0.1",
        "loguru==0.7.3",
        "matplotlib==3.10.1",
        "nbformat==5.10.4",
        "numpy==2.2.3",
        "openml==0.15.1",
        "pandas==2.2.3",
        "plotly==5.24.1",
        "pmlb==1.0.1.post3",
        "protobuf==6.30.1",
        "psutil==6.1.1",
        "pyAgrum==1.17.2",
        "python-dotenv==1.0.1",
        "Requests==2.32.3",
        "SALib==1.5.1",
        "scikit_learn==1.3.2",
        "scipy==1.15.2",
        "setuptools==75.5.0",
        "shap==0.46.0",
        "six==1.17.0",
        "slicer==0.0.8",
        "Sphinx==8.2.3",
        "sphinx_rtd_theme==3.0.2",
        "SQLAlchemy==1.4.44",
        "sqlalchemy_utils==0.41.2",
        "stopit==1.1.2",
        "streamlit==1.43.2",
        "torch==2.6.0",
        "tqdm==4.66.2",
        "traitlets==5.14.3",
        "treeinterpreter==0.2.3"
    ],
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.6",
)
